### ISSUE TITLE
Ran the auto installer and getting error

### ISSUE THREAD

**Issue by geekedtv** [l3alr0g/Slashboard-pulsar#16]
Error

The authenticity of host 'github.com (140.82.114.3)' can't be established.ted to /pulsar/Slashboard-pulsar/node_modules/.staging/type-is-546f807e (97ms)

**Comment by l3alr0g** [comment]
Hi,
Can you please provide the full log returned by the script ?
Also, are you executing `scripts/install.sh` or scripts/update.sh` ?
