### ISSUE TITLE
[Bug]: Can't run Pulser

### ISSUE THREAD

**Issue by yuan-chan** [l3alr0g/Slashboard-pulsar#23]
### Contact Details

yuan@white-paper.jp

### What happened ?

pm2 shows an error and cannot be executed.
I was able to run it in the previous version.

### How can we reproduce it ?

run "pm2 start ecosystem.config.js --env production"

### Relevant log output

```shell
0|Pulsar  | WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
0|Pulsar  | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
0|Pulsar  | WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
0|Pulsar  | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
0|Pulsar  | { Error: Cannot find module 'node:crypto'
0|Pulsar  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
0|Pulsar  |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
```

### Code of Conduct

- [x] I agree to follow Pulsar's Code of Conduct

**Comment by l3alr0g** [comment]
This seems to be an issue linked to the latest security improvement, the module node:crypto was first introduced in node 15.x . Can you try upgrading to node 16.10.0 ? If this still fails with node 16.x, then I'll need the full log to understand what is actually happening.

**Comment by yuan-chan** [comment]
I was able to work by updating node to 16.10.0! Thank you very much!
